apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: playwright-runner
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: playwright
          image: shahrid92/sr-playwirght-worker
          #command: ["npm","run","test"]

  pollingInterval: 5
  maxReplicaCount: 20

  triggers:
  - type: redis
    metadata:
      address: redis-master:6379
      listName: playwright-shards
      listLength: "1"