FROM mcr.microsoft.com/playwright:v1.50.1-noble

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . ./


ENTRYPOINT ["sh", "-c", "echo 'PWD:' && pwd && echo 'LS:' && ls -al && exec \"$@\"", "--"]

CMD ["sh", "-c", "npx playwright test --grep @smoke --list project=chromium"]